### ISSUE TITLE
Circular Dependency when API served out of `/api` in the URL

### ISSUE THREAD

**Issue by joemccall86** [ePages-de/restdocs-raml#25]
Our api is exposed at `/api/...` in our running application. When we run `ramldoc` it generates an `api.raml` that references `api.raml`, creating a circular dependency. I believe this can be mitigated by allowing the `outputFileNamePrefix` to be configurable in `build.gradle`.

**Comment by mduesterhoeft** [comment]
Thanks for reporting the issue - seems like I overlooked this.

I will try to come up with a fix very soon.

**Comment by mduesterhoeft** [comment]
Please check the new version `0.3.0` there is a new `outputFileNamePrefix` configuration option to customize the name of the top-level RAML file. Additionally we now check that a group file will not have the same name as the top-level file. So it should also work for you without adding this configuration.
